### ISSUE TITLE
[Question] Controlling mob spawn duration

### ISSUE THREAD

**Issue by mpustovoi** [wendall911/BetterDays#35]
So I have that 'Man From the Fog' mod on my Forge 1.20.1-47.4.0 installation. It's a MCreator mod, but the config really works.
This mod has a config for adjusting spawn rate (he spawns at night):
```toml

["Server and Client"]
	#enable spawning of the man
	enable_spawning = true
	#minimum duration of spawning in ticks
	min_spawn_rate = 72000.0
	#maximum duration of spawning in ticks
	max_spawn_rate = 168000.0
        # ...
```

I have 30 minutes of day & night length with Better Days and its working absolutely fine:
```toml
[time]
	daySpeed = 0.3333333333333333
	nightSpeed = 0.3333333333333333
        # ...
```

I just wanted to ask what tick values should I put in MFTF's config so he appears every 3-7 in-game nights?
I multiplied default day tick lengths (24000) by 3 and 7, got these values above.

Maybe, I just didn't notice him, but we've played already 10 days and he didn't appear once.
